# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 601741e27cd50c3bd54f7aea4740924c776a2b150148e1b2e898db1ab1e47722e71bc1cb6e9fa88362a00af29322cefd809a569a1765f33e67f449fc96116758

test:
  secret_key_base: 84f61120f670c458c0f8e6e91e17fea4aa44a9c584d47f801099e66c38544cd64699caaacd1265f17c811b3241710e1abde24773dadd67fde95837058c8dbfff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
